templateDir: "/aioRunbook/templates/"
runbookDirs: "/runbooks"
httpPort: 4711
sftpPort: 4713
sftpServerHostKeyFile: "/aioRunbook/id_rsa"
userAuth:
- - username: test
  - password: test
  - permissions: 
    - viewResults
    - runTests
    - editTests
pdfOutput:
  author: SL
  pdfResultDir: /aioRunbook/results_pdfTests
  template: /aioRunbook/templates/template2.tex